### ISSUE TITLE
Implementations of function Mock.assertAnyCallMatches and Mock.assertAnyCallMatches contain error

### ISSUE THREAD

**Issue by jinminglee** [henry4k/lua-mock#5]
@henry4k 
`
function Mock:assertCallMatches( query )
    self.spy.assertCallMatches(query)  <----------- should be 'self.spy:'
    return self
end

function Mock:assertAnyCallMatches( query )
    self.spy.assertAnyCallMatches(query) <-----------  should be 'self.spy:'
    return self
end
`

**Comment by henry4k** [comment]
Thanks! Fixed it and uploaded the new version to luarocks :+1:
